### PR TITLE
Update for standards and to 3.3a.

### PR DESCRIPTION
**Pull request by ScottBailey**
Updated to version 3.3a.
Updated standards.
Updated dependencies.
Added to aggregate.

Source: https://github.com/tmux/tmux

### CODE REVIEW

**Review by katietz — CHANGES_REQUESTED** [review]
Two things I see why it fails on osx.
First you should add libutf8proc to run dependencies too.
Second issue is the syntax of the "no server" test.  This won't work on osx as on a linux in all cases.  So I would use the check for "no server" just for our linux (docker) builds.  It could be btw that on our osx builders a server is actually running

**Review by varlackc — COMMENTED** [review]
https://github.com/AnacondaRecipes/tmux-feedstock/blob/b99d89a7af64deb65885babd762818f7ddcce2e2/recipe/meta.yaml#L43

We might need to see if the skip in the `|| true` on the test is truly necessary. Is it that the tests are trully broken? or do we have to make some corrections on the package?

**Comment by ScottBailey** [comment]
> $(tmux info || true) 2> >(grep "no server running on")

This is not a skip. We expect `tmux info` to fail and then we are looking for stderr output to be something containing "no server running on". I believe this syntax keeps the test from failing.

**Comment by ScottBailey** [comment]
> Two things I see why it fails on osx. First you should add libutf8proc to run dependencies too. Second issue is the syntax of the "no server" test. This won't work on osx as on a linux in all cases. So I would use the check for "no server" just for our linux (docker) builds. It could be btw that on our osx builders a server is actually running

This seems to be the case. Removed the test for OSX.

**Pull request merged**
